server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: Baidu1234!
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  devtools:
    restart:
      enabled: true
      additional-exclude: src/main/java
      exclude: src/main/resource
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
    virtual-host: /
    listener:
      simple:
          prefetch: 5
          acknowledge-mode: manual
          retry:
            enabled: true # 开启消费者失败重试
            initial-interval: 1000ms # 初始的失败等待时长为1秒
            multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval（类似csma-cd）
            max-attempts: 3 # 最大重试次数
            stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false
      template:
        mandatory: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug